// <auto-generated />
using System;
using ChefkochScraper;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChefkochScraper.Migrations
{
    [DbContext(typeof(ChefkochContext))]
    [Migration("20240723000554_02")]
    partial class _02
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("ChefkochScraper.FullRecipeTag", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("FullTags");
                });

            modelBuilder.Entity("ChefkochScraper.Ingredient", b =>
                {
                    b.Property<Guid>("LocalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("IngredientGroupLocalId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LocalCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LocalModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("amount")
                        .HasColumnType("REAL");

                    b.Property<string>("blsKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("foodId")
                        .HasColumnType("TEXT");

                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("isBasic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("previewImageUrlTemplate")
                        .HasColumnType("TEXT");

                    b.Property<string>("productGroup")
                        .HasColumnType("TEXT");

                    b.Property<string>("unit")
                        .HasColumnType("TEXT");

                    b.Property<string>("unitId")
                        .HasColumnType("TEXT");

                    b.Property<string>("url")
                        .HasColumnType("TEXT");

                    b.Property<string>("usageInfo")
                        .HasColumnType("TEXT");

                    b.HasKey("LocalId");

                    b.HasIndex("IngredientGroupLocalId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("ChefkochScraper.IngredientGroup", b =>
                {
                    b.Property<Guid>("LocalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LocalCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LocalModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("header")
                        .HasColumnType("TEXT");

                    b.HasKey("LocalId");

                    b.ToTable("IngredientGroups");
                });

            modelBuilder.Entity("ChefkochScraper.Nutrition", b =>
                {
                    b.Property<Guid>("LocalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LocalCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LocalModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("carbohydrateContent")
                        .HasColumnType("REAL");

                    b.Property<double?>("fatContent")
                        .HasColumnType("REAL");

                    b.Property<int?>("kCalories")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("proteinContent")
                        .HasColumnType("REAL");

                    b.HasKey("LocalId");

                    b.ToTable("Nutrition");
                });

            modelBuilder.Entity("ChefkochScraper.Rating", b =>
                {
                    b.Property<Guid>("LocalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LocalCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LocalModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("numVotes")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("rating")
                        .HasColumnType("REAL");

                    b.HasKey("LocalId");

                    b.ToTable("Rating");
                });

            modelBuilder.Entity("ChefkochScraper.RecipeModel", b =>
                {
                    b.Property<Guid>("LocalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LocalCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LocalModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("additionalDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("affiliateContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("categoryIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("cookingTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("createdAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("editorLocalId")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("hasImage")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("hasVideo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("imageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ingredientsText")
                        .HasColumnType("TEXT");

                    b.Property<string>("instructions")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("isIndexable")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("isPlus")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("isPremium")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("isRejected")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("isSubmitted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("kCalories")
                        .HasColumnType("INTEGER");

                    b.Property<string>("metaDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("metaTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("miscellaneousText")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("nutritionLocalId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ownerLocalId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("preparationTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("previewImageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("previewImageOwnerLocalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("previewImageUrlTemplate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ratingLocalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("recipeVideoId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("restingTime")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("servings")
                        .HasColumnType("INTEGER");

                    b.Property<string>("siteUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("slug")
                        .HasColumnType("TEXT");

                    b.Property<int?>("status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("submissionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("subtitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.Property<int?>("totalTime")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("type")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("viewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("LocalId");

                    b.HasIndex("editorLocalId");

                    b.HasIndex("nutritionLocalId");

                    b.HasIndex("ownerLocalId");

                    b.HasIndex("previewImageOwnerLocalId");

                    b.HasIndex("ratingLocalId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("ChefkochScraper.UserModel", b =>
                {
                    b.Property<Guid>("LocalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LocalCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LocalModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("avatarImageUrlTemplate")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("displayName")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("hasAvatar")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("hasPaid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("isVerified")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("rank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("role")
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .HasColumnType("TEXT");

                    b.HasKey("LocalId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ChefkochScraper.Ingredient", b =>
                {
                    b.HasOne("ChefkochScraper.IngredientGroup", null)
                        .WithMany("ingredients")
                        .HasForeignKey("IngredientGroupLocalId");
                });

            modelBuilder.Entity("ChefkochScraper.RecipeModel", b =>
                {
                    b.HasOne("ChefkochScraper.UserModel", "editor")
                        .WithMany()
                        .HasForeignKey("editorLocalId");

                    b.HasOne("ChefkochScraper.Nutrition", "nutrition")
                        .WithMany()
                        .HasForeignKey("nutritionLocalId");

                    b.HasOne("ChefkochScraper.UserModel", "owner")
                        .WithMany()
                        .HasForeignKey("ownerLocalId");

                    b.HasOne("ChefkochScraper.UserModel", "previewImageOwner")
                        .WithMany()
                        .HasForeignKey("previewImageOwnerLocalId");

                    b.HasOne("ChefkochScraper.Rating", "rating")
                        .WithMany()
                        .HasForeignKey("ratingLocalId");

                    b.Navigation("editor");

                    b.Navigation("nutrition");

                    b.Navigation("owner");

                    b.Navigation("previewImageOwner");

                    b.Navigation("rating");
                });

            modelBuilder.Entity("ChefkochScraper.IngredientGroup", b =>
                {
                    b.Navigation("ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
