// <auto-generated />
using System;
using ChefkochScraper;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChefkochScraper.Migrations
{
    [DbContext(typeof(ChefkochContext))]
    [Migration("20240722235549_01")]
    partial class _01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("ChefkochScraper.FullRecipeTag", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("FullTags");
                });

            modelBuilder.Entity("ChefkochScraper.Ingredient", b =>
                {
                    b.Property<Guid>("LocalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("IngredientGroupLocalId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LocalCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LocalModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("amount")
                        .HasColumnType("REAL");

                    b.Property<string>("blsKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("foodId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isBasic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("previewImageUrlTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("productGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("unitId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("usageInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LocalId");

                    b.HasIndex("IngredientGroupLocalId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("ChefkochScraper.IngredientGroup", b =>
                {
                    b.Property<Guid>("LocalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LocalCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LocalModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("header")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LocalId");

                    b.ToTable("IngredientGroups");
                });

            modelBuilder.Entity("ChefkochScraper.Nutrition", b =>
                {
                    b.Property<Guid>("LocalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LocalCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LocalModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("carbohydrateContent")
                        .HasColumnType("REAL");

                    b.Property<double>("fatContent")
                        .HasColumnType("REAL");

                    b.Property<int>("kCalories")
                        .HasColumnType("INTEGER");

                    b.Property<double>("proteinContent")
                        .HasColumnType("REAL");

                    b.HasKey("LocalId");

                    b.ToTable("Nutrition");
                });

            modelBuilder.Entity("ChefkochScraper.Rating", b =>
                {
                    b.Property<Guid>("LocalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LocalCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LocalModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("numVotes")
                        .HasColumnType("INTEGER");

                    b.Property<double>("rating")
                        .HasColumnType("REAL");

                    b.HasKey("LocalId");

                    b.ToTable("Rating");
                });

            modelBuilder.Entity("ChefkochScraper.RecipeModel", b =>
                {
                    b.Property<Guid>("LocalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LocalCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LocalModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("additionalDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("affiliateContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("categoryIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("cookingTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("createdAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("editorLocalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("hasImage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("hasVideo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("imageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ingredientsText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("instructions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isIndexable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isPlus")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isPremium")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isRejected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isSubmitted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("kCalories")
                        .HasColumnType("INTEGER");

                    b.Property<string>("metaDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("metaTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("miscellaneousText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("nutritionLocalId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ownerLocalId")
                        .HasColumnType("TEXT");

                    b.Property<int>("preparationTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("previewImageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("previewImageOwnerLocalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("previewImageUrlTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ratingLocalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("recipeVideoId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("restingTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("servings")
                        .HasColumnType("INTEGER");

                    b.Property<string>("siteUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("submissionDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("subtitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("totalTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("viewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("LocalId");

                    b.HasIndex("editorLocalId");

                    b.HasIndex("nutritionLocalId");

                    b.HasIndex("ownerLocalId");

                    b.HasIndex("previewImageOwnerLocalId");

                    b.HasIndex("ratingLocalId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("ChefkochScraper.UserModel", b =>
                {
                    b.Property<Guid>("LocalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LocalCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LocalModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("avatarImageUrlTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("displayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("hasAvatar")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("hasPaid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isVerified")
                        .HasColumnType("INTEGER");

                    b.Property<int>("rank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LocalId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ChefkochScraper.Ingredient", b =>
                {
                    b.HasOne("ChefkochScraper.IngredientGroup", null)
                        .WithMany("ingredients")
                        .HasForeignKey("IngredientGroupLocalId");
                });

            modelBuilder.Entity("ChefkochScraper.RecipeModel", b =>
                {
                    b.HasOne("ChefkochScraper.UserModel", "editor")
                        .WithMany()
                        .HasForeignKey("editorLocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChefkochScraper.Nutrition", "nutrition")
                        .WithMany()
                        .HasForeignKey("nutritionLocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChefkochScraper.UserModel", "owner")
                        .WithMany()
                        .HasForeignKey("ownerLocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChefkochScraper.UserModel", "previewImageOwner")
                        .WithMany()
                        .HasForeignKey("previewImageOwnerLocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChefkochScraper.Rating", "rating")
                        .WithMany()
                        .HasForeignKey("ratingLocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("editor");

                    b.Navigation("nutrition");

                    b.Navigation("owner");

                    b.Navigation("previewImageOwner");

                    b.Navigation("rating");
                });

            modelBuilder.Entity("ChefkochScraper.IngredientGroup", b =>
                {
                    b.Navigation("ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
